services:
  wra:
    build:
      context: wra
      target: final
    ports:
      - 8079:8079
    environment:
      WRA_PROXY_TARGET: "http://vulnapp:5000"
      WRA_REDIS_ADDR: "redis:6379"
    restart: unless-stopped

  admin_back:
    build:
      context: wra-admin-back
      target: final
    ports:
      - 8080:8080
    restart: unless-stopped

  admin_front:
    build: wra-admin-front
    ports:
      - 3000:3000
    restart: unless-stopped


  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped


  postgres:
    image: postgres:16
    container_name: wra-postgres
    restart: always
    environment:
      POSTGRES_USER: wra
      POSTGRES_PASSWORD: wra
      POSTGRES_DB: wra
    ports:
      - "5432:5432"

  vulnapp:
    build: wra-example-app
    ports:
      - "5000:5000"
    restart: unless-stopped

